import ctypes
import os.path
import os

#this is a windows hack.
#we want it to find out libsndfile before the system one, so we do this.
libsndfile_module = ctypes.cdll.LoadLibrary(os.path.join(os.path.split(os.path.abspath(__file__))[0], 'libsndfile-1.dll'))
libaudioverse_module = ctypes.cdll.LoadLibrary(os.path.join(os.path.split(os.path.abspath(__file__))[0], 'libaudioverse.dll'))

Lav_ERROR_INTERNAL = 999
Lav_OBJTYPE_SINE = 5
Lav_OBJTYPE_GENERIC = 0
Lav_ERROR_INVALID_SLOT = 3
Lav_MAX_BLOCK_SIZE = 1024
Lav_ERROR_NO_OUTPUTS = 13
Lav_OBJTYPE_MIXER = 6
Lav_PROPERTYTYPE_FLOAT_ARRAY = 7
Lav_DELAY_FEEDBACK = -3
Lav_ERROR_CANNOT_INIT_AUDIO = 7
Lav_ERROR_MEMORY = 5
Lav_OBJTYPE_WORLD = 1
Lav_OBJECT_SUSPENDED = -100
Lav_FILE_PITCH_BEND = -2
Lav_PANNER_CHANNEL_MAP = -3
Lav_ERROR_RANGE = 6
Lav_ATTENUATOR_MULTIPLIER = -1
Lav_SOURCE_DISTANCE_MODEL = -4
Lav_ERROR_FILE_NOT_FOUND = 9
Lav_FILE_END_CALLBACK = -1
Lav_FILE_LOOPING = -3
Lav_SOURCE_MAX_DISTANCE = -3
Lav_DISTANCE_MODEL_EXPONENTIAL = 1
Lav_SINE_FREQUENCY = -1
Lav_OBJTYPE_HRTF = 4
Lav_MIXER_INPUTS_PER_PARENT = -2
Lav_3D_POSITION = -2
Lav_ERROR_NONE = 0
Lav_PROPERTYTYPE_INT = 1
Lav_PROPERTYTYPE_INT_ARRAY = 8
Lav_ERROR_SHAPE = 11
Lav_PANNER_ELEVATION = -2
Lav_ERROR_NULL_POINTER = 4
Lav_OBJTYPE_FILE = 3
Lav_ERROR_HRTF_INVALID = 10
Lav_DELAY_INTERPOLATION_TIME = -4
Lav_OBJTYPE_HARD_LIMITER = 8
Lav_PROPERTYTYPE_DOUBLE = 3
Lav_OBJTYPE_AMPLITUDE_PANNER = 10
Lav_DISTANCE_MODEL_LINEAR = 0
Lav_ERROR_CANNOT_CROSS_DEVICES = 12
Lav_ERROR_CAUSES_CYCLE = 15
Lav_DELAY_DELAY_MAX = -2
Lav_ERROR_LIMIT_EXCEEDED = 14
Lav_ERROR_FILE = 8
Lav_PROPERTYTYPE_FLOAT3 = 5
Lav_3D_ORIENTATION = -1
Lav_PROPERTYTYPE_FLOAT6 = 6
Lav_PROPERTYTYPE_STRING = 4
Lav_PANNER_AZIMUTH = -1
Lav_ERROR_UNKNOWN = 1
Lav_OBJTYPE_ATTENUATOR = 7
Lav_MIXER_MAX_PARENTS = -1
Lav_DISTANCE_MODEL_INVERSE_SQUARE = 2
Lav_DELAY_DELAY = -1
Lav_OBJTYPE_SOURCE = 2
Lav_OBJTYPE_DELAY = 9
Lav_PROPERTYTYPE_FLOAT = 2
Lav_ERROR_TYPE_MISMATCH = 2
Lav_FILE_POSITION = -1

LavSimulation = None
LavObject = None
LavError = ctypes.c_int
LavLimits = ctypes.c_int
LavPropertyType = ctypes.c_int
LavObjectType = ctypes.c_int
LavEventCallback = ctypes.CFUNCTYPE(None, ctypes.POINTER(LavObject), ctypes.c_void_p)

Lav_initializeLibrary = ctypes.CFUNCTYPE(LavError)(('Lav_initializeLibrary', libaudioverse_module))
Lav_free = ctypes.CFUNCTYPE(LavError, ctypes.c_void_p)(('Lav_free', libaudioverse_module))
Lav_deviceGetCount = ctypes.CFUNCTYPE(LavError, ctypes.POINTER(ctypes.c_uint))(('Lav_deviceGetCount', libaudioverse_module))
Lav_deviceGetLatency = ctypes.CFUNCTYPE(LavError, ctypes.c_uint, ctypes.POINTER(ctypes.c_float))(('Lav_deviceGetLatency', libaudioverse_module))
Lav_deviceGetName = ctypes.CFUNCTYPE(LavError, ctypes.c_uint, ctypes.POINTER(ctypes.c_char_p))(('Lav_deviceGetName', libaudioverse_module))
Lav_deviceGetChannels = ctypes.CFUNCTYPE(LavError, ctypes.c_uint, ctypes.POINTER(ctypes.c_uint))(('Lav_deviceGetChannels', libaudioverse_module))
Lav_createSimulationForDevice = ctypes.CFUNCTYPE(LavError, ctypes.c_int, ctypes.c_uint, ctypes.c_uint, ctypes.c_uint, ctypes.POINTER(ctypes.POINTER(LavSimulation)))(('Lav_createSimulationForDevice', libaudioverse_module))
Lav_createReadSimulation = ctypes.CFUNCTYPE(LavError, ctypes.c_uint, ctypes.c_uint, ctypes.c_uint, ctypes.POINTER(ctypes.POINTER(LavSimulation)))(('Lav_createReadSimulation', libaudioverse_module))
Lav_simulationSetOutputObject = ctypes.CFUNCTYPE(LavError, ctypes.POINTER(LavSimulation), ctypes.POINTER(LavObject))(('Lav_simulationSetOutputObject', libaudioverse_module))
Lav_simulationGetOutputObject = ctypes.CFUNCTYPE(LavError, ctypes.POINTER(LavSimulation), ctypes.POINTER(ctypes.POINTER(LavObject)))(('Lav_simulationGetOutputObject', libaudioverse_module))
Lav_simulationGetBlockSize = ctypes.CFUNCTYPE(LavError, ctypes.POINTER(LavSimulation), ctypes.POINTER(ctypes.c_int))(('Lav_simulationGetBlockSize', libaudioverse_module))
Lav_simulationGetBlock = ctypes.CFUNCTYPE(LavError, ctypes.POINTER(LavSimulation), ctypes.POINTER(ctypes.c_float))(('Lav_simulationGetBlock', libaudioverse_module))
Lav_simulationGetSr = ctypes.CFUNCTYPE(LavError, ctypes.POINTER(LavSimulation), ctypes.POINTER(ctypes.c_int))(('Lav_simulationGetSr', libaudioverse_module))
Lav_simulationGetChannels = ctypes.CFUNCTYPE(LavError, ctypes.POINTER(LavSimulation), ctypes.POINTER(ctypes.c_int))(('Lav_simulationGetChannels', libaudioverse_module))
Lav_objectGetType = ctypes.CFUNCTYPE(LavError, ctypes.POINTER(LavObject), ctypes.POINTER(ctypes.c_int))(('Lav_objectGetType', libaudioverse_module))
Lav_objectGetInputCount = ctypes.CFUNCTYPE(LavError, ctypes.POINTER(LavObject), ctypes.POINTER(ctypes.c_uint))(('Lav_objectGetInputCount', libaudioverse_module))
Lav_objectGetOutputCount = ctypes.CFUNCTYPE(LavError, ctypes.POINTER(LavObject), ctypes.POINTER(ctypes.c_uint))(('Lav_objectGetOutputCount', libaudioverse_module))
Lav_objectGetInputObject = ctypes.CFUNCTYPE(LavError, ctypes.POINTER(LavObject), ctypes.c_uint, ctypes.POINTER(ctypes.POINTER(LavObject)))(('Lav_objectGetInputObject', libaudioverse_module))
Lav_objectGetInputOutput = ctypes.CFUNCTYPE(LavError, ctypes.POINTER(LavObject), ctypes.c_uint, ctypes.POINTER(ctypes.c_uint))(('Lav_objectGetInputOutput', libaudioverse_module))
Lav_objectSetInput = ctypes.CFUNCTYPE(LavError, ctypes.POINTER(LavObject), ctypes.c_uint, ctypes.POINTER(LavObject), ctypes.c_uint)(('Lav_objectSetInput', libaudioverse_module))
Lav_objectResetProperty = ctypes.CFUNCTYPE(LavError, ctypes.POINTER(LavObject), ctypes.c_int)(('Lav_objectResetProperty', libaudioverse_module))
Lav_objectSetIntProperty = ctypes.CFUNCTYPE(LavError, ctypes.POINTER(LavObject), ctypes.c_int, ctypes.c_int)(('Lav_objectSetIntProperty', libaudioverse_module))
Lav_objectSetFloatProperty = ctypes.CFUNCTYPE(LavError, ctypes.POINTER(LavObject), ctypes.c_int, ctypes.c_float)(('Lav_objectSetFloatProperty', libaudioverse_module))
Lav_objectSetDoubleProperty = ctypes.CFUNCTYPE(LavError, ctypes.POINTER(LavObject), ctypes.c_int, ctypes.c_double)(('Lav_objectSetDoubleProperty', libaudioverse_module))
Lav_objectSetStringProperty = ctypes.CFUNCTYPE(LavError, ctypes.POINTER(LavObject), ctypes.c_int, ctypes.c_char_p)(('Lav_objectSetStringProperty', libaudioverse_module))
Lav_objectSetFloat3Property = ctypes.CFUNCTYPE(LavError, ctypes.POINTER(LavObject), ctypes.c_int, ctypes.c_float, ctypes.c_float, ctypes.c_float)(('Lav_objectSetFloat3Property', libaudioverse_module))
Lav_objectSetFloat6Property = ctypes.CFUNCTYPE(LavError, ctypes.POINTER(LavObject), ctypes.c_int, ctypes.c_float, ctypes.c_float, ctypes.c_float, ctypes.c_float, ctypes.c_float, ctypes.c_float)(('Lav_objectSetFloat6Property', libaudioverse_module))
Lav_objectGetIntProperty = ctypes.CFUNCTYPE(LavError, ctypes.POINTER(LavObject), ctypes.c_int, ctypes.POINTER(ctypes.c_int))(('Lav_objectGetIntProperty', libaudioverse_module))
Lav_objectGetFloatProperty = ctypes.CFUNCTYPE(LavError, ctypes.POINTER(LavObject), ctypes.c_int, ctypes.POINTER(ctypes.c_float))(('Lav_objectGetFloatProperty', libaudioverse_module))
Lav_objectGetDoubleProperty = ctypes.CFUNCTYPE(LavError, ctypes.POINTER(LavObject), ctypes.c_int, ctypes.POINTER(ctypes.c_double))(('Lav_objectGetDoubleProperty', libaudioverse_module))
Lav_objectGetStringProperty = ctypes.CFUNCTYPE(LavError, ctypes.POINTER(LavObject), ctypes.c_int, ctypes.POINTER(ctypes.c_char_p))(('Lav_objectGetStringProperty', libaudioverse_module))
Lav_objectGetFloat3Property = ctypes.CFUNCTYPE(LavError, ctypes.POINTER(LavObject), ctypes.c_int, ctypes.POINTER(ctypes.c_float), ctypes.POINTER(ctypes.c_float), ctypes.POINTER(ctypes.c_float))(('Lav_objectGetFloat3Property', libaudioverse_module))
Lav_objectGetFloat6Property = ctypes.CFUNCTYPE(LavError, ctypes.POINTER(LavObject), ctypes.c_int, ctypes.POINTER(ctypes.c_float), ctypes.POINTER(ctypes.c_float), ctypes.POINTER(ctypes.c_float), ctypes.POINTER(ctypes.c_float), ctypes.POINTER(ctypes.c_float), ctypes.POINTER(ctypes.c_float))(('Lav_objectGetFloat6Property', libaudioverse_module))
Lav_objectGetIntPropertyRange = ctypes.CFUNCTYPE(LavError, ctypes.POINTER(LavObject), ctypes.c_int, ctypes.POINTER(ctypes.c_int), ctypes.POINTER(ctypes.c_int))(('Lav_objectGetIntPropertyRange', libaudioverse_module))
Lav_objectGetFloatPropertyRange = ctypes.CFUNCTYPE(LavError, ctypes.POINTER(LavObject), ctypes.c_int, ctypes.POINTER(ctypes.c_float), ctypes.POINTER(ctypes.c_float))(('Lav_objectGetFloatPropertyRange', libaudioverse_module))
Lav_objectGetDoublePropertyRange = ctypes.CFUNCTYPE(LavError, ctypes.POINTER(LavObject), ctypes.c_int, ctypes.POINTER(ctypes.c_double), ctypes.POINTER(ctypes.c_double))(('Lav_objectGetDoublePropertyRange', libaudioverse_module))
Lav_objectGetPropertyIndices = ctypes.CFUNCTYPE(LavError, ctypes.POINTER(LavObject), ctypes.POINTER(ctypes.POINTER(ctypes.c_int)))(('Lav_objectGetPropertyIndices', libaudioverse_module))
Lav_objectGetPropertyName = ctypes.CFUNCTYPE(LavError, ctypes.POINTER(LavObject), ctypes.c_int, ctypes.POINTER(ctypes.c_char_p))(('Lav_objectGetPropertyName', libaudioverse_module))
Lav_objectReplaceFloatArrayProperty = ctypes.CFUNCTYPE(LavError, ctypes.POINTER(LavObject), ctypes.c_int, ctypes.c_uint, ctypes.POINTER(ctypes.c_float))(('Lav_objectReplaceFloatArrayProperty', libaudioverse_module))
Lav_objectReadFloatArrayProperty = ctypes.CFUNCTYPE(LavError, ctypes.POINTER(LavObject), ctypes.c_int, ctypes.c_uint, ctypes.POINTER(ctypes.c_float))(('Lav_objectReadFloatArrayProperty', libaudioverse_module))
Lav_objectWriteFloatArrayProperty = ctypes.CFUNCTYPE(LavError, ctypes.POINTER(LavObject), ctypes.c_int, ctypes.c_uint, ctypes.c_uint, ctypes.POINTER(ctypes.c_float))(('Lav_objectWriteFloatArrayProperty', libaudioverse_module))
Lav_objectGetFloatArrayPropertyDefault = ctypes.CFUNCTYPE(LavError, ctypes.POINTER(LavObject), ctypes.c_int, ctypes.POINTER(ctypes.c_uint), ctypes.POINTER(ctypes.POINTER(ctypes.c_float)))(('Lav_objectGetFloatArrayPropertyDefault', libaudioverse_module))
Lav_objectGetFloatArrayPropertyLength = ctypes.CFUNCTYPE(LavError, ctypes.POINTER(LavObject), ctypes.c_int, ctypes.POINTER(ctypes.c_uint))(('Lav_objectGetFloatArrayPropertyLength', libaudioverse_module))
Lav_objectReplaceIntArrayProperty = ctypes.CFUNCTYPE(LavError, ctypes.POINTER(LavObject), ctypes.c_int, ctypes.c_uint, ctypes.POINTER(ctypes.c_int))(('Lav_objectReplaceIntArrayProperty', libaudioverse_module))
Lav_objectReadIntArrayProperty = ctypes.CFUNCTYPE(LavError, ctypes.POINTER(LavObject), ctypes.c_int, ctypes.c_uint, ctypes.POINTER(ctypes.c_int))(('Lav_objectReadIntArrayProperty', libaudioverse_module))
Lav_objectWriteIntArrayProperty = ctypes.CFUNCTYPE(LavError, ctypes.POINTER(LavObject), ctypes.c_int, ctypes.c_uint, ctypes.c_uint, ctypes.POINTER(ctypes.c_int))(('Lav_objectWriteIntArrayProperty', libaudioverse_module))
Lav_objectGetIntArrayPropertyDefault = ctypes.CFUNCTYPE(LavError, ctypes.POINTER(LavObject), ctypes.c_int, ctypes.POINTER(ctypes.c_uint), ctypes.POINTER(ctypes.POINTER(ctypes.c_int)))(('Lav_objectGetIntArrayPropertyDefault', libaudioverse_module))
Lav_objectGetIntArrayPropertyLength = ctypes.CFUNCTYPE(LavError, ctypes.POINTER(LavObject), ctypes.c_int, ctypes.POINTER(ctypes.c_int))(('Lav_objectGetIntArrayPropertyLength', libaudioverse_module))
Lav_objectGetArrayPropertyLengthRange = ctypes.CFUNCTYPE(LavError, ctypes.POINTER(LavObject), ctypes.c_int, ctypes.POINTER(ctypes.c_uint), ctypes.POINTER(ctypes.c_uint))(('Lav_objectGetArrayPropertyLengthRange', libaudioverse_module))
Lav_objectGetCallbackHandler = ctypes.CFUNCTYPE(LavError, ctypes.POINTER(LavObject), ctypes.c_int, ctypes.POINTER(LavEventCallback))(('Lav_objectGetCallbackHandler', libaudioverse_module))
Lav_objectGetCallbackUserDataPointer = ctypes.CFUNCTYPE(LavError, ctypes.POINTER(LavObject), ctypes.c_int, ctypes.POINTER(ctypes.c_void_p))(('Lav_objectGetCallbackUserDataPointer', libaudioverse_module))
Lav_objectSetCallback = ctypes.CFUNCTYPE(LavError, ctypes.POINTER(LavObject), ctypes.c_int, LavEventCallback, ctypes.c_void_p)(('Lav_objectSetCallback', libaudioverse_module))
Lav_createSineObject = ctypes.CFUNCTYPE(LavError, ctypes.POINTER(LavSimulation), ctypes.POINTER(ctypes.POINTER(LavObject)))(('Lav_createSineObject', libaudioverse_module))
Lav_createFileObject = ctypes.CFUNCTYPE(LavError, ctypes.POINTER(LavSimulation), ctypes.c_char_p, ctypes.POINTER(ctypes.POINTER(LavObject)))(('Lav_createFileObject', libaudioverse_module))
Lav_createHrtfObject = ctypes.CFUNCTYPE(LavError, ctypes.POINTER(LavSimulation), ctypes.c_char_p, ctypes.POINTER(ctypes.POINTER(LavObject)))(('Lav_createHrtfObject', libaudioverse_module))
Lav_createMixerObject = ctypes.CFUNCTYPE(LavError, ctypes.POINTER(LavSimulation), ctypes.c_uint, ctypes.c_uint, ctypes.POINTER(ctypes.POINTER(LavObject)))(('Lav_createMixerObject', libaudioverse_module))
Lav_createAttenuatorObject = ctypes.CFUNCTYPE(LavError, ctypes.POINTER(LavSimulation), ctypes.c_uint, ctypes.POINTER(ctypes.POINTER(LavObject)))(('Lav_createAttenuatorObject', libaudioverse_module))
Lav_createHardLimiterObject = ctypes.CFUNCTYPE(LavError, ctypes.POINTER(LavSimulation), ctypes.c_uint, ctypes.POINTER(ctypes.POINTER(LavObject)))(('Lav_createHardLimiterObject', libaudioverse_module))
Lav_createDelayObject = ctypes.CFUNCTYPE(LavError, ctypes.POINTER(LavSimulation), ctypes.c_uint, ctypes.POINTER(ctypes.POINTER(LavObject)))(('Lav_createDelayObject', libaudioverse_module))
Lav_createAmplitudePannerObject = ctypes.CFUNCTYPE(LavError, ctypes.POINTER(LavSimulation), ctypes.POINTER(ctypes.POINTER(LavObject)))(('Lav_createAmplitudePannerObject', libaudioverse_module))
Lav_createWorldObject = ctypes.CFUNCTYPE(LavError, ctypes.POINTER(LavSimulation), ctypes.c_char_p, ctypes.POINTER(ctypes.POINTER(LavObject)))(('Lav_createWorldObject', libaudioverse_module))
Lav_createSourceObject = ctypes.CFUNCTYPE(LavError, ctypes.POINTER(LavSimulation), ctypes.POINTER(LavObject), ctypes.POINTER(ctypes.POINTER(LavObject)))(('Lav_createSourceObject', libaudioverse_module))
