sudo: required
dist: trusty
language: cpp

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
            - gcc-4.9
      env:
        - CXX_COMPILER=g++-4.9
        - C_COMPILER = gcc-4.9

before_install:
  #This comes from travis CI issue 5326.
  - export PATH=$(echo $PATH | tr ':' "\n" | sed '/\/opt\/python/d' | tr "\n" ":" | sed "s|::|:|g")
  - sudo apt-get update -qq
  - sudo apt-get install -y libasound2-dev libboost-all-dev python3-numpy python3-scipy libsndfile1-dev pandoc python3-pip python3-yaml
  - sudo python3 -m pip install pycparser jinja2 pypandoc

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_CXX_COMPILER=$CXX_COMPILER -DCMAKE_C_COMPILER=$C_COMPILER .. && make

